### ISSUE TITLE
Build error on Mac OSX

### ISSUE THREAD

**Issue by llbit** [rho-devel/rho#88]
I merged Arun's branch into the current master branch and tried to build on OSX with clang 3.6. I get this build error:

```
In file included from ../../../src/main/names.cpp:40:
In file included from ../../../src/include/Internal.h:40:
../../../src/include/rho/BuiltInFunction.hpp:524:6: error: definition with same mangled
      name as another definition
            TableEntry(const char* name, FUNCTION function,
            ^
../../../src/include/rho/BuiltInFunction.hpp:524:6: note: previous definition is here
../../../src/include/rho/BuiltInFunction.hpp:524:6: error: definition with same mangled
      name as another definition
            TableEntry(const char* name, FUNCTION function,
            ^
../../../src/include/rho/BuiltInFunction.hpp:524:6: note: previous definition is here
```

The line it complains about is the declaration of the `TableEntry` constructor. The constructor is templated and is used only as a convenience to construct table entries for the builtin function table. Here is the entirety of the `TableEntry` struct:

```
  struct TableEntry {
            template<typename FUNCTION>
            TableEntry(const char* name, FUNCTION function,
                       unsigned int variant, unsigned int flags, int arity,
                       PPinfo ppinfo,
                       const char* first_arg_name = nullptr,
                       DispatchType dispatch = DispatchType::NONE)
                : function(new BuiltInFunction(name, function, variant,
                                               flags, arity, ppinfo,
                                               s_next_offset++,
                                               first_arg_name, dispatch))
            {}
            BuiltInFunction* function;
            static unsigned int s_next_offset;
        };
```

It seems like it should be possible to remove the `TableEntry` struct and instead constructing builtin functions directly could solve the compile error. The `s_next_offset` counter would need to be moved to `BuiltInFunction` instead.

**Comment by llbit** [comment]
Refactoring to remove `TableEntry` fixed this particular build problem, but now I get undefined reference errors instead which seem unrelated to the above issue.

**Comment by llbit** [comment]
Here are the current build errors:

```
Undefined symbols for architecture x86_64:
  "locale2charset(char const*)", referenced from:
      Ri18n_iswupper(int) in rlocale.o
      Ri18n_iswlower(int) in rlocale.o
      Ri18n_iswalpha(int) in rlocale.o
      Ri18n_iswdigit(int) in rlocale.o
      Ri18n_iswxdigit(int) in rlocale.o
      Ri18n_iswspace(int) in rlocale.o
      Ri18n_iswprint(int) in rlocale.o
      ...
  "ucol_getLocaleByType(UCollator const*, ULocDataLocaleType, int*)", referenced from:
      do_ICUget(rho::RObject*, rho::RObject*, rho::RObject*, rho::RObject*) in util.o
  "typeinfo for llvm::Instruction", referenced from:
      rho::JIT::RemoveRedundantCallsToSetVisibility::runOnBasicBlock(llvm::BasicBlock&) in libjit.a(Optimization.o)
  "typeinfo for llvm::FunctionPass", referenced from:
      typeinfo for rho::JIT::BasicFunctionPass in libjit.a(Optimization.o)
  "typeinfo for llvm::BasicBlockPass", referenced from:
      typeinfo for rho::JIT::RemoveRedundantCallsToSetVisibility in libjit.a(Optimization.o)
  "typeinfo for llvm::TerminatorInst", referenced from:
      rho::JIT::Compiler::emitEval(rho::RObject const*) in libjit.a(Compiler.o)
  "typeinfo for llvm::SectionMemoryManager", referenced from:
      typeinfo for rho::JIT::MCJITMemoryManager in libjit.a(MCJITMemoryManager.o)
  "typeinfo for llvm::Value", referenced from:
      rho::JIT::Compiler::emitEval(rho::RObject const*) in libjit.a(Compiler.o)
      rho::JIT::Compiler::emitExpressionEval(rho::Expression const*) in libjit.a(Compiler.o)
      rho::JIT::Compiler::emitInlineableBuiltinCall(rho::Expression const*, llvm::Value*, rho::FunctionBase*) in libjit.a(Compiler.o)
  "typeinfo for llvm::CallInst", referenced from:
      rho::JIT::RemoveRedundantCallsToSetVisibility::runOnBasicBlock(llvm::BasicBlock&) in libjit.a(Optimization.o)
  "typeinfo for llvm::Constant", referenced from:
      rho::JIT::Compiler::emitExpressionEval(rho::Expression const*) in libjit.a(Compiler.o)
      rho::JIT::Compiler::emitInlineableBuiltinCall(rho::Expression const*, llvm::Value*, rho::FunctionBase*) in libjit.a(Compiler.o)
```

**Comment by llbit** [comment]
I am building with Clang 3.6.2.

**Comment by llbit** [comment]
The undefined symbol `locale2charset` error is strange since `src/main/localecharset.cpp` defines `locale2charset`. However, when I look at the symbol table for `localecharset.o` I get

```
$ nm src/main/localecharset.o 
                 U __DefaultRuneLocale
0000000000000780 s __ZL5known
0000000000007850 b __ZZ14locale2charsetE7charset
                 U ___maskrune
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___tolower
                 U ___toupper
                 U _atoi
0000000000000000 T _locale2charset
                 U _setlocale
                 U _snprintf
                 U _strcmp
                 U _strlen
                 U _strncmp
                 U _strncpy
                 U _strrchr
```

So some name mangling is happening, but I'm not sure why.

**Comment by kmillar** [comment]
The llvm errors will be because llvm is build without typeinfo on some
platforms.  We'll need rewrite all code that uses it (dynamic_cast is the
most common case).

**Comment by kmillar** [comment]
The problem with locale2charset is that in some places it's treated as
'extern "C"', but not everywhere.  localecharset.o has the regular name,
and the link error is where the code is looking for the mangled name.

**Comment by llbit** [comment]
Adding `extern "C"` to `locale2charset` fixed that link error, and the LLVM link errors remain.

**Comment by llbit** [comment]
I don't know how to fix this one:

```
Undefined symbols for architecture x86_64:
  "ucol_getLocaleByType(UCollator const*, ULocDataLocaleType, int*)", referenced from:
      do_ICUget(rho::RObject*, rho::RObject*, rho::RObject*, rho::RObject*) in util.o
```

Apparently the header `unicode/ucol.h` is not available on OSX, but in `util.cpp` the prototype for the above function is declared anyway.

**Comment by kmillar** [comment]
It looks like util.cpp is misdeclaring UErrorCode on line 1792.

You could either fix it or change the functions to 'extern "C"' to use the
icu C API instead of the C++ one (warning: I'm not 100% sure the later
option works)

**Comment by ArunChauhan** [comment]
My notes indicate that I needed to install the icu package on OS X through MacPorts.  May be, there is a way to avoid that.

**Comment by llbit** [comment]
I did not install an icu package, afaik.

I'm down to these linker errors now after replacing a few `dynamic_cast<>` by `llvm::dyn_cast<>`:

```
Undefined symbols for architecture x86_64:
  "typeinfo for llvm::FunctionPass", referenced from:
      typeinfo for rho::JIT::BasicFunctionPass in libjit.a(Optimization.o)
  "typeinfo for llvm::BasicBlockPass", referenced from:
      typeinfo for rho::JIT::RemoveRedundantCallsToSetVisibility in libjit.a(Optimization.o)
  "typeinfo for llvm::SectionMemoryManager", referenced from:
      typeinfo for rho::JIT::MCJITMemoryManager in libjit.a(MCJITMemoryManager.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by llbit** [comment]
The remaining link errors seem to be caused by deriving LLVM classes compiled without RTTI and attempting to build derived classes with RTTI. I could try to build LLVM from source with RTTI enabled.

**Comment by kmillar** [comment]
It'd be much better if we can find a way to make it work without end-users
needing to install something as big as LLVM from source.  I'd be very
surprised if there isn't a simple way to do this, otherwise LLVM wouldn't
be built this way.

**Comment by ArunChauhan** [comment]
Optimization.o is my code.  I am currently heavily editing it and while I am at it I am also changing the dyamic_cast to llvm:dyn_cast.  Hopefully, that should fix the problem related to it.

If you did make that change already then it might be worth clearing your build directory and rebuilding from scratch, just to make sure you don't have some stale cache lying around.

**Comment by llbit** [comment]
I don't think it is possible to replace all `dynamic_cast` by `llvm:dyn_cast`, I think that would only work for types derived from LLVM base types.

**Comment by ArunChauhan** [comment]
Sure, but LLVM types are the only ones that cause the problems, right?  Optimization.cpp uses dynamic_cast for LLVM types, so it can be replaced by llvm:dyn_cast.

**Comment by kmillar** [comment]
IIRC (it's a while since I've looked) the LLVM type casting mechanism is
extensible, so it should work with our types as well.

**Comment by llbit** [comment]
I just re-installed LLVM using Homebrew and the `--with-rttti` option, and that fixed the linker errors:

```
brew install --with-clang --with-rtti llvm
```

The build now fails on installing `sysdata.rda`:

```
mkdir ../../../../library/tools/libs
installing 'sysdata.rda'
error: Unknown attribute kind (45)
```

**Comment by llbit** [comment]
I tried copying `RuntimeImpl.bc` from a Linux-built version of Rho, and get this build error now:

```
installing 'sysdata.rda'
warning: ignoring debug info with an invalid version (1) in /Users/joqvist/git/rho/build5/jit/RuntimeImpl.bc
Assertion failed: (m_engine), function CompiledExpression, file ../../../../src/main/jit/CompiledExpression.cpp, line 116.
/bin/sh: line 1:  6590 Done                    echo "tools:::sysdata2LazyLoadDB(\"../../../../src/library/tools/R/sysdata.rda\",\"../../../library/tools/R\")"
      6591 Abort trap: 6           | R_DEFAULT_PACKAGES=NULL LC_ALL=C ../../../bin/R --vanilla --slave
```

**Comment by llbit** [comment]
Building without `--enable-llvm-jit` worked, except that I got one error complaining about missing `lzma.h` even though I had installed the `xz` package with Homebrew and added the Homebrew include directory to the compile flags. Running make after the first error then ran okay until this point:

```
'pdflatex' is needed to make vignettes but is missing on your system.
configuring Java ...
Java interpreter : /usr/bin/java
No Java runtime present, requesting install.


*** Java interpreter doesn't work properly.

make[1]: [stamp-java] Error 1 (ignored)
```

The rho interpreter seems to run right now.

**Comment by llbit** [comment]
Here is the build error caused by missing `lzma.h` when I ran make the first time:

```
/Library/Developer/CommandLineTools/usr/bin/make utils-pkg grDevices-pkg graphics-pkg stats-pkg datasets-pkg methods-pkg grid-pkg splines-pkg stats4-pkg tcltk-pkg parallel-pkg
/Library/Developer/CommandLineTools/usr/bin/make -C utils all
/Library/Developer/CommandLineTools/usr/bin/make -C grDevices all
building package 'utils'
building package 'grDevices'
mkdir ../../../library/utils
mkdir ../../../library/grDevices
mkdir ../../../library/utils/doc
mkdir ../../../library/grDevices/R
mkdir ../../../library/utils/R
mkdir ../../../library/utils/Sweave
mkdir ../../../library/utils/misc
making init.d from ../../../../../src/library/utils/src/init.c
mkdir ../../../library/grDevices/afm
making sock.d from ../../../../../src/library/utils/src/sock.c
making stubs.d from ../../../../../src/library/utils/src/stubs.c
making utils.d from ../../../../../src/library/utils/src/utils.c
../../../../../src/library/utils/src/utils.c:56:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated
```

Here are the relevant steps that led to the error:

```
brew install xz
...
CC='clang' CXX='clang++' CFLAGS='-I/Users/joqvist/homebrew/include -g -O2' CXXFLAGS='-I/Users/joqvist/homebrew/include -g -O2' LDFLAGS='-L/Users/joqvist/homebrew/lib' ../configure --with-blas --with-lapack --with-x=no
make -j2 --no-print-directory
```

**Comment by llbit** [comment]
The `utils.c` file only uses a single declaration from `lzma.h`, so we could just replace the include there with a forward declaration. Maybe not the best solution, but I can't see a nice way to pass on the include directory where I have my `lzma.h` to the Makefile for the utils library.

**Comment by kmillar** [comment]
It ought to be (but isn't) an option to configure.

Since it isn't, the obvious thing to do would be to add the -I<directory>
to CPPFLAGS when running configure.

**Comment by llbit** [comment]
Defining `CPPFLAGS` worked. I thought it would be enough to set `CXXFLAGS`, what is the difference between the two?

I can build Rho now without JIT enabled, but I think `make check` still has problems.

**Comment by kmillar** [comment]
`CPPFLAGS` is used for preprocessor flags, while `CXXFLAGS` is used for C++ flags.  It's unfortunate that `CPPFLAGS` looks like it means `C++FLAGS`.

So for C code like utils.c, it'll be compiled with `CPPFLAGS` and `CFLAGS`, but not `CXXFLAGS`.
